# Stage 1: Build Angular App
FROM node:18-alpine AS build
WORKDIR /usr/src/app

# Copy package files
COPY frontend/package*.json ./

# Install dependencies
RUN npm install

# Copy all frontend source code
COPY frontend/ .

# Build Angular app
RUN npm run build --prod

# Stage 2: Nginx Serve
FROM nginx:stable-alpine

# Copy Angular dist output to Nginx html folder
COPY --from=build /usr/src/app/dist/angular-15-crud/ /usr/share/nginx/html/

# Copy Nginx config
COPY nginx/default.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
